
name: konstankino-diff-actor
description: diffs the code
branding:
  icon: "activity"
  color: "blue"
  
on: [push]

runs:
  using: "composite"
  steps:
    - name: Run the differ
      shell: bash
      run:  |
        git diff $SHA_BEFORE $SHA_AFTER > most-recent.diff
        cat most-recent.diff
        # curl -X POST -H "x-api-key: $API_KEY" -H "Content-Type: text/xml" --data-binary "@most-recent.diff" --header "Name: $AUTHOR_NAME" --header "Email: $AUTHOR_EMAIL" --header "Username: $AUTHOR_USERNAME" --header "Repository: $REPOSITORY" $API_ENDPOINT/$AUTHOR_USERNAME/$SHA_AFTER
