
name: konstankino-diff-actor
description: diffs the code
branding:
  icon: "activity"
  color: "blue"

runs:
  using: "composite"
  steps:
    - name: Run the differ
      shell: bash
      run:  |
        git diff $SHA_BEFORE $SHA_AFTER > most-recent.diff

        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        SHA_AFTER=$(jq --raw-output .pull_request.head.sha "$GITHUB_EVENT_PATH")
        SHA_BEFORE$=$(jq --raw-output .pull_request.base.sha "$GITHUB_EVENT_PATH")
        AUTHOR_USERNAME=$(jq --raw-output .pull_request.user.login "$GITHUB_EVENT_PATH")
        REPOSITORY=${{ github.event.payload.repository.full_name }}
        EVENT_TITLE=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")
        
        echo $REPOSITORY
        
        curl -X POST -H "x-api-key: $API_KEY" -H "Content-Type: text/xml" --data-binary "@most-recent.diff" --header "Title: $EVENT_TITLE" --header "Username: $AUTHOR_USERNAME" --header "Repository: $REPOSITORY" $API_ENDPOINT/pull-request/$PR_NUMBER
