
name: konstankino-diff-actor
description: diffs the code
branding:
  icon: "activity"
  color: "blue"
  
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run the differ
        run:  |
          git diff ${{ inputs.sha_before }} ${{ inputs.sha_after }} > most-recent.diff
          curl -X POST -H "x-api-key: ${{ inputs.api_key }}" -H "Content-Type: text/xml" --data-binary "@most-recent.diff" --header "Name: ${{inputs.author_name}}" --header "Email: ${{inputs.author_email}}" --header "Username: ${{inputs.author_username}}" --header "Repository: ${{ inputs.repository }}" ${{ inputs.endpoint }}/${{inputs.actor}}/${{inputs.sha_after}}
          
